import type { Metadata } from "next";

import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: {
    template: "%s | Ecome",
    default: "Ecome",
  },
  generator: "Milad",
  applicationName: "Ecomme",
  referrer: "origin-when-cross-origin",
  keywords: ["Next.js", "React", "JavaScript", "ecomm"],
  authors: [{ name: "Milad" }, { name: "Milad", url: "https://nextjs.org" }],
  creator: "Jiachi Liu",
  publisher: "Sebastian Markbåge",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
